### PR TITLE
Make the tests pass with Python 3.13.0a1

### PR DESCRIPTION
**Pull request by hroncok**
The badsyntax_pep3120.py file has been moved upstream.

https://github.com/python/cpython/commit/4dd47c63a97b3c39cd964ad12431fcdaf76dc823

zombie hand raises from a grave

### CODE REVIEW

**Comment by encukou** [comment]
Since https://github.com/python/devguide/issues/1168, test fixes are backported to all branches.

IMO, we need to ~~bury~~ copy the file next to the zombie-imp test.

**Comment by hroncok** [comment]
Done.

**Comment by hroncok** [comment]
The Ci failure seems transient (dnf metadata download error).

**Comment by encukou** [comment]
Thank you!

**Pull request merged**
